# Generated by Django 2.2.10 on 2021-11-17 10:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FireAlarmMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('altert', models.CharField(blank=True, max_length=50, null=True)),
                ('model', models.CharField(blank=True, max_length=50, null=True, verbose_name='型号')),
                ('status', models.IntegerField(blank=True, null=True, verbose_name='状态')),
                ('protocol', models.CharField(blank=True, max_length=50, null=True, verbose_name='协议')),
            ],
            options={
                'verbose_name': '电气火灾设备基本信息',
                'verbose_name_plural': '电气火灾设备基本信息',
                'db_table': 'db_fireAlarmMessage',
            },
        ),
        migrations.CreateModel(
            name='FireAlarmData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='盒子id')),
                ('datetime', models.DateTimeField(default=datetime.datetime.now, verbose_name='数据更新时间')),
                ('volt_a', models.FloatField(blank=True, null=True, verbose_name='电压A相')),
                ('volt_b', models.FloatField(blank=True, null=True, verbose_name='电压B相')),
                ('volt_c', models.FloatField(blank=True, null=True, verbose_name='电压C相')),
                ('current_a', models.FloatField(blank=True, null=True, verbose_name='电流A相')),
                ('current_b', models.FloatField(blank=True, null=True, verbose_name='电流B相')),
                ('current_c', models.FloatField(blank=True, null=True, verbose_name='电流C相')),
                ('current_l', models.FloatField(blank=True, null=True, verbose_name='漏电流')),
                ('temp_a', models.FloatField(blank=True, null=True, verbose_name='温度A相')),
                ('temp_b', models.FloatField(blank=True, null=True, verbose_name='温度B相')),
                ('temp_c', models.FloatField(blank=True, null=True, verbose_name='温度C相')),
                ('temp_l', models.FloatField(blank=True, null=True, verbose_name='温度L相')),
                ('temp_n', models.FloatField(blank=True, null=True, verbose_name='温度N相')),
                ('power_a', models.FloatField(blank=True, null=True, verbose_name='功率A相')),
                ('power_b', models.FloatField(blank=True, null=True, verbose_name='功率B相')),
                ('power_c', models.FloatField(blank=True, null=True, verbose_name='功率C相')),
                ('pfa', models.FloatField(blank=True, null=True, verbose_name='功率因数A相')),
                ('pfb', models.FloatField(blank=True, null=True, verbose_name='功率因数B相')),
                ('pfc', models.FloatField(blank=True, null=True, verbose_name='功率因数C相')),
                ('release_status', models.IntegerField(blank=True, choices=[(0, '关'), (1, '开')], null=True, verbose_name='脱扣器状态')),
                ('power_wh', models.FloatField(blank=True, null=True, verbose_name='电镀')),
                ('status', models.IntegerField(blank=True, choices=[(15, '正常'), (16, '告警')], null=True, verbose_name='机器状态')),
                ('fire_alarm_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fireAlarm.FireAlarmMessage')),
            ],
            options={
                'verbose_name': '电气火灾设备数据',
                'verbose_name_plural': '电气火灾设备数据',
                'db_table': 'db_FireAlarmData',
            },
        ),
    ]
