# Generated by Django 2.2.10 on 2021-11-17 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fireAlarm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firealarmdata',
            old_name='datetime',
            new_name='update_time',
        ),
    ]
