# Generated by Django 2.2.10 on 2021-11-22 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fireAlarm', '0003_get_firealarm'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Get_FireAlarm',
            new_name='Box_FireAlarm',
        ),
        migrations.AlterModelTable(
            name='box_firealarm',
            table='db_Box_FireAlarm',
        ),
    ]
