# Generated by Django 2.2.10 on 2021-11-17 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('humiture', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='humituremessage',
            options={'verbose_name': '温湿度信息', 'verbose_name_plural': '温湿度信息'},
        ),
        migrations.AlterModelTable(
            name='humituremessage',
            table='db_HumitureMessage',
        ),
    ]
