# Generated by Django 2.2.10 on 2021-11-17 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humiture', '0002_auto_20211117_1006'),
    ]

    operations = [
        migrations.CreateModel(
            name='HumitureEquipmentMsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(5, '网络离线'), (6, '设备离线'), (7, '正常'), (8, '告警'), (15, '正常'), (16, '告警')], default=6, verbose_name='状态')),
                ('protocol', models.CharField(blank=True, max_length=50, null=True, verbose_name='协议')),
                ('altert', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': '温湿度设备信息',
                'verbose_name_plural': '温湿度设备信息',
                'db_table': 'db_HumitureEquipmentMsg',
            },
        ),
        migrations.DeleteModel(
            name='HumitureMessage',
        ),
    ]
