# Generated by Django 2.2.10 on 2021-11-17 10:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('humiture', '0003_auto_20211117_1017'),
    ]

    operations = [
        migrations.CreateModel(
            name='HumitureThreshold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_la', models.IntegerField(blank=True, null=True)),
                ('temp_lr', models.IntegerField(blank=True, null=True)),
                ('temp_ha', models.IntegerField(blank=True, null=True)),
                ('temp_hr', models.IntegerField(blank=True, null=True)),
                ('humidity_la', models.IntegerField(blank=True, null=True)),
                ('humidity_lr', models.IntegerField(blank=True, null=True)),
                ('humidity_ha', models.IntegerField(blank=True, null=True)),
                ('humidity_hr', models.IntegerField(blank=True, null=True)),
                ('box_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='盒子序号')),
                ('device_id', models.CharField(blank=True, max_length=30, null=True, verbose_name='设备序号')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '温湿度阈值',
                'verbose_name_plural': '温湿度阈值',
                'db_table': 'db_HumitureThreshold',
            },
        ),
        migrations.CreateModel(
            name='HumitureSensorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(blank=True, null=True, verbose_name='温湿度序号')),
                ('status', models.IntegerField(blank=True, null=True, verbose_name='状态')),
                ('temp', models.FloatField(blank=True, null=True, verbose_name='温度')),
                ('mac', models.CharField(blank=True, max_length=50, null=True, verbose_name='云盒编码')),
                ('humidity', models.FloatField(blank=True, null=True, verbose_name='湿度')),
                ('device_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='设备名称')),
                ('altert', models.CharField(blank=True, max_length=50, null=True)),
                ('device_id', models.CharField(blank=True, max_length=10, null=True, verbose_name='设备序号')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
                ('humiture_equipment_msg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='humiture.HumitureEquipmentMsg')),
            ],
            options={
                'verbose_name': '温湿度传感器数据',
                'verbose_name_plural': '温湿度传感器数据',
                'db_table': 'db_HumitureSensorData',
            },
        ),
    ]
