# Generated by Django 2.2.10 on 2021-11-22 10:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humiture', '0004_humituresensordata_humiturethreshold'),
    ]

    operations = [
        migrations.CreateModel(
            name='Get_Humiture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
                ('str_data', models.CharField(max_length=500, verbose_name='温湿度数据')),
            ],
            options={
                'verbose_name': '温湿度API数据',
                'verbose_name_plural': '温湿度API数据',
                'db_table': 'db_Get_Humiture',
            },
        ),
    ]
