# Generated by Django 2.2.10 on 2021-11-22 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('humiture', '0005_get_humiture'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Get_Humiture',
            new_name='Box_Humiture',
        ),
        migrations.AlterModelTable(
            name='box_humiture',
            table='db_Box_Humiture',
        ),
    ]
