# Generated by Django 2.2.10 on 2021-11-17 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InductorMsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(blank=True, max_length=30, null=True, verbose_name='云盒编码')),
                ('status', models.IntegerField(choices=[(5, '网络离线'), (6, '设备离线'), (9, '正常'), (10, '告警'), (15, '正常'), (16, '告警')], default=6, verbose_name='状态')),
                ('type', models.IntegerField(blank=True, null=True)),
                ('in1', models.IntegerField(blank=True, null=True)),
                ('in2', models.IntegerField(blank=True, null=True)),
                ('out1', models.IntegerField(blank=True, null=True)),
                ('out2', models.IntegerField(blank=True, null=True)),
                ('altert', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '传感器设备',
                'verbose_name_plural': '传感器设备',
                'db_table': 'db_InductorMsg',
            },
        ),
    ]
