# Generated by Django 2.2.10 on 2021-11-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inductor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'db_test',
            },
        ),
    ]
