# Generated by Django 2.2.10 on 2021-11-17 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inductor', '0002_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
