# Generated by Django 2.2.10 on 2021-11-22 10:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inductor', '0003_delete_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Get_Inductor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
                ('str_data', models.CharField(max_length=500, verbose_name='传感器数据')),
            ],
            options={
                'verbose_name': '传感器API数据',
                'verbose_name_plural': '传感器API数据',
                'db_table': 'db_Get_Inductor',
            },
        ),
    ]
