# Generated by Django 2.2.10 on 2021-11-22 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inductor', '0004_get_inductor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Get_Inductor',
            new_name='Box_Inductor',
        ),
        migrations.AlterModelTable(
            name='box_inductor',
            table='db_Box_Inductor',
        ),
    ]
