# Generated by Django 2.2.10 on 2021-11-17 10:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CloudAlarm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_lr', models.IntegerField(blank=True, null=True, verbose_name='低温解除阈值')),
                ('temp_hr', models.IntegerField(blank=True, null=True, verbose_name='高温解除阈值')),
                ('temp_la', models.IntegerField(blank=True, null=True, verbose_name='低温告警阈值')),
                ('temp_ha', models.IntegerField(blank=True, null=True, verbose_name='高温告警阈值')),
                ('volt_la', models.FloatField(blank=True, null=True, verbose_name='欠压告警阈值')),
                ('volt_hr', models.FloatField(blank=True, null=True, verbose_name='过压解除阈值')),
                ('volt_lr', models.FloatField(blank=True, null=True, verbose_name='欠压解除阈值')),
                ('volt_ha', models.FloatField(blank=True, null=True, verbose_name='过压告警阈值')),
                ('current_detection', models.IntegerField(blank=True, null=True, verbose_name='电流检测')),
                ('curr_ratio', models.IntegerField(blank=True, null=True, verbose_name='电流比率')),
                ('resistance_hr', models.IntegerField(blank=True, null=True, verbose_name='内阻高解除阈值')),
                ('resistance_ha', models.IntegerField(blank=True, null=True, verbose_name='内阻高告警阈值')),
                ('bat_group_num', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '云系统告警阈值',
                'verbose_name_plural': '云系统告警阈值',
                'db_table': 'db_CloudAlarm',
            },
        ),
        migrations.CreateModel(
            name='BatteryState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('altert', models.CharField(blank=True, max_length=50, null=True)),
                ('master', models.IntegerField(blank=True, null=True)),
                ('current', models.FloatField(blank=True, null=True, verbose_name='电流')),
                ('agent', models.IntegerField(blank=True, null=True, verbose_name='代理')),
                ('status', models.IntegerField(choices=[(5, '网络离线'), (6, '设备离线'), (11, '正常'), (12, '告警'), (15, '正常'), (16, '告警')], default=6, verbose_name='状态')),
                ('temp', models.FloatField(blank=True, null=True, verbose_name='环境温度')),
                ('volt', models.FloatField(blank=True, null=True, verbose_name='总电压')),
                ('cloud_alarm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battery.CloudAlarm')),
            ],
            options={
                'verbose_name': '电池基本状态',
                'verbose_name_plural': '电池基本状态',
                'db_table': 'db_BatteryState',
            },
        ),
        migrations.CreateModel(
            name='BatteryMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volt', models.IntegerField(blank=True, null=True, verbose_name='单节电池电压')),
                ('volt1', models.IntegerField(blank=True, null=True, verbose_name='单节电池电压1')),
                ('volt2', models.IntegerField(blank=True, null=True, verbose_name='单节电池电压2')),
                ('volt3', models.IntegerField(blank=True, null=True, verbose_name='单节电池电压3')),
                ('volt4', models.IntegerField(blank=True, null=True, verbose_name='单节电池电压4')),
                ('tmpture1', models.FloatField(blank=True, null=True, verbose_name='单节电池温度1')),
                ('tmpture2', models.FloatField(blank=True, null=True, verbose_name='单节电池温度2')),
                ('temp', models.FloatField(blank=True, null=True, verbose_name='单节电池温度')),
                ('current', models.FloatField(blank=True, null=True, verbose_name='电流')),
                ('resistance', models.FloatField(blank=True, null=True, verbose_name='单节电池电阻')),
                ('bat_status', models.IntegerField(blank=True, null=True, verbose_name='状态')),
                ('mac', models.CharField(blank=True, max_length=50, null=True)),
                ('altert', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('cell_altert', models.CharField(blank=True, max_length=50, null=True)),
                ('datetime', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='更新时间')),
                ('order_id', models.IntegerField(blank=True, null=True)),
                ('device_id', models.IntegerField(blank=True, null=True)),
                ('battery_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battery.BatteryState')),
            ],
            options={
                'verbose_name': '电池基本信息',
                'verbose_name_plural': '电池基本信息',
                'db_table': 'db_BatteryMessage',
            },
        ),
    ]
