# Generated by Django 2.2.10 on 2021-11-22 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battery', '0003_get_batterydata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='get_batterydata',
            options={'verbose_name': '电池数据', 'verbose_name_plural': '电池数据'},
        ),
        migrations.AlterModelTable(
            name='get_batterydata',
            table='db_Get_BatteryData',
        ),
    ]
