# Generated by Django 2.2.10 on 2021-11-17 10:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirConditionerData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, '正常'), (2, '告警'), (5, '网络离线'), (6, '设备离线'), (15, '正常')], default=6, verbose_name='状态')),
                ('preset_humidity', models.IntegerField(blank=True, null=True, verbose_name='空调预设湿度')),
                ('discharge_pressure', models.IntegerField(blank=True, null=True, verbose_name='排放压强')),
                ('actual_humidity', models.IntegerField(blank=True, null=True, verbose_name='回风湿度')),
                ('fluid_temp_in', models.IntegerField(blank=True, null=True)),
                ('net_status', models.IntegerField(blank=True, null=True, verbose_name='网络状态')),
                ('altert', models.CharField(blank=True, max_length=50, null=True)),
                ('cmp_drv_speed', models.IntegerField(blank=True, null=True)),
                ('mac', models.CharField(blank=True, max_length=50, null=True, verbose_name='云盒编码')),
                ('air_flow', models.IntegerField(blank=True, null=True)),
                ('cool_dmd', models.IntegerField(blank=True, null=True)),
                ('power_source', models.IntegerField(blank=True, null=True)),
                ('rack_temp_3', models.IntegerField(blank=True, null=True)),
                ('cool_out', models.IntegerField(blank=True, null=True)),
                ('rack_inlet_temp', models.IntegerField(blank=True, null=True)),
                ('rack_temp_1', models.IntegerField(blank=True, null=True)),
                ('preset_temp', models.IntegerField(blank=True, null=True, verbose_name='空调预设温度')),
                ('filter_dp', models.IntegerField(blank=True, null=True)),
                ('supply_temp', models.IntegerField(blank=True, null=True)),
                ('fluid_flow', models.IntegerField(blank=True, null=True)),
                ('suction_pressure', models.IntegerField(blank=True, null=True)),
                ('actual_temp', models.IntegerField(blank=True, null=True, verbose_name='回风温度')),
                ('acfan', models.IntegerField(blank=True, null=True, verbose_name='风机')),
                ('rack_temp_2', models.IntegerField(blank=True, null=True)),
                ('cmp_drv_coltage', models.IntegerField(blank=True, null=True)),
                ('cmp_drv_power', models.IntegerField(blank=True, null=True)),
                ('fluid_temp_out', models.IntegerField(blank=True, null=True)),
                ('temp', models.IntegerField(choices=[(1, '制冷'), (1, '制热')], default=1, verbose_name='制冷/制热')),
                ('fluid_valve_pos', models.IntegerField(blank=True, null=True)),
                ('fan_speed', models.IntegerField(blank=True, null=True)),
                ('humidity', models.IntegerField(choices=[(1, '除湿'), (2, '加湿')], default=1, verbose_name='除湿/加湿')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '精密空调数据',
                'verbose_name_plural': '精密空调数据',
                'db_table': 'db_airConditionerData',
            },
        ),
    ]
