# Generated by Django 2.2.10 on 2021-11-22 09:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airConditioner', '0002_auto_20211118_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='Get_AirConditionerData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
                ('str_data', models.CharField(max_length=500, verbose_name='空调数据')),
            ],
        ),
        migrations.AlterField(
            model_name='airconditionerdata',
            name='humidity',
            field=models.CharField(blank=True, choices=[(1, '除湿'), (2, '加湿')], max_length=10, null=True, verbose_name='除湿/加湿'),
        ),
        migrations.AlterField(
            model_name='airconditionerdata',
            name='temp',
            field=models.CharField(blank=True, choices=[(1, '制冷'), (1, '制热')], max_length=10, null=True, verbose_name='制冷/制热'),
        ),
    ]
