# Generated by Django 2.2.10 on 2021-11-22 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airConditioner', '0003_auto_20211122_0949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='get_airconditionerdata',
            options={'verbose_name': '空调api获取', 'verbose_name_plural': '空调api获取'},
        ),
        migrations.AlterModelTable(
            name='get_airconditionerdata',
            table='db_Get_AirConditionerData',
        ),
    ]
