# Generated by Django 2.2.10 on 2021-11-22 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airConditioner', '0004_auto_20211122_0953'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Get_AirConditionerData',
            new_name='Get_AirConditioner',
        ),
    ]
