# Generated by Django 2.2.10 on 2021-11-22 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airConditioner', '0005_auto_20211122_1023'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Get_AirConditioner',
            new_name='Box_AirConditioner',
        ),
        migrations.AlterModelTable(
            name='box_airconditioner',
            table='db_Box_AirConditioner',
        ),
    ]
